server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    register-with-eureka: false
    fetch-registry: false
  server:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  instadnce: 
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health