eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
consumer:
  ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 3000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 4
    MaxAutoRetries: 1
    ServerListRefreshInterval: 5000
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true